# Generated by Django 4.2 on 2023-09-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JudgeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField()),
                ('finished', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight_from', models.IntegerField()),
                ('weight_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1_score', models.IntegerField()),
                ('member2_score', models.IntegerField()),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.judge')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.match')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('belt_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.belt')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.team')),
                ('weight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.weightclass')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='member1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='competition.member'),
        ),
        migrations.AddField(
            model_name='match',
            name='member2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='competition.member'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='competition.member'),
        ),
        migrations.CreateModel(
            name='JudgeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.judge')),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.judgequalification'),
        ),
        migrations.CreateModel(
            name='CompetitionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.member')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='first_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_place', to='competition.member'),
        ),
        migrations.AddField(
            model_name='competition',
            name='second_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_place', to='competition.member'),
        ),
        migrations.AddField(
            model_name='competition',
            name='third_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_place', to='competition.member'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.team')),
            ],
        ),
    ]
