# Generated by Django 4.2 on 2023-09-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='first_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_place', to='competition.member'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='second_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_place', to='competition.member'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='third_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_place', to='competition.member'),
        ),
    ]
