# Generated by Django 4.2 on 2023-11-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_remove_competitioncategory_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
