# Generated by Django 4.2 on 2023-11-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_competition_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
