# Generated by Django 4.2 on 2023-09-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_competition_first_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='competitions',
            field=models.ManyToManyField(through='competition.CompetitionMembership', to='competition.competition'),
        ),
    ]
