# Generated by Django 4.2 on 2023-11-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_alter_member_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
