# Generated by Django 4.2 on 2023-11-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_alter_match_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmember',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
