# Generated by Django 4.2 on 2023-11-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_alter_matchmember_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchmember',
            unique_together={('match', 'member')},
        ),
    ]
