# Generated by Django 4.2 on 2023-11-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_alter_matchmember_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.IntegerField(choices=[(1, '1/16'), (2, '1/8'), (3, '1/4'), (4, '1/2'), (5, 'Final')], default=1),
        ),
        migrations.AlterField(
            model_name='matchmember',
            name='status',
            field=models.CharField(choices=[(1, 'Win'), (2, 'Lose'), (3, 'Disqualified')], max_length=255),
        ),
    ]
