# Generated by Django 4.2 on 2023-11-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_alter_matchmember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmember',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not started'), (1, 'Win'), (2, 'Lose'), (3, 'Disqualified')]),
        ),
    ]
