# Generated by Django 4.2 on 2023-11-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_alter_matchmember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rating',
            field=models.IntegerField(default=1000),
        ),
    ]
